### ISSUE TITLE
Will this support urls with -nocookie?

### ISSUE THREAD

**Issue by Findiglay** [KaneCohen/embed#10]
Will this support youtube urls with -nocookie attached? It seems to return false.

**Comment by KaneCohen** [comment]
Just to be sure, you mean youtube-nocookie.com domain?

No that url type is not in the list of default providers. However if you wish to always use -nocookie you could modify embed config file should be saved in config/embed.php and modify line 96:

````php
// From
'src' => {protocol}://www.youtube.com/embed/{1}?rel=0&wmode=transparent
// To
'src' => {protocol}://www.youtube-nocookie.com/embed/{1}?rel=0&wmode=transparent
````

I don't think I'll be adding `nocookie` as a default provider since usually shareable links lead to normal domain name for youtube and other providers don't support nocookie.

**Comment by Findiglay** [comment]
Hi thanks for the quick reply!

Yes that's exactly it. I've run into the issue described here on latest iOS versions where videos are being launched automatically if the YouTube app is installed:
http://stackoverflow.com/questions/29794859/embedded-youtube-videos-in-html5-standalone-app-ios-8-3-opening-youtube-app

**Comment by KaneCohen** [comment]
Well as I mentioned fix is easy to implement in embed.php config file. You can also apply similar fix for YouTube playlists and other cases if they are available,

**Comment by Findiglay** [comment]
This solved the issue. Thank you for the assistance!
